version: "3"

services:
  broker:
    container_name: broker
    build:
      context: .
      dockerfile: ./apps/broker/Dockerfile
    volumes:
      - ./apps/broker:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 1883:1883
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: yarn run start:debug
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - ./apps/auth:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    command: yarn run start
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
