http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: "*"
serviceEndpoints:
  devices:
    url: "http://devices:3000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: devices
              changeOrigin: true
